# Generated by Django 2.2.7 on 2019-11-16 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gobiernoapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comm_content', models.CharField(max_length=500)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('dislikes', models.PositiveIntegerField(default=0)),
                ('poli_id', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Comments',
                'ordering': ['id'],
            },
        ),
        migrations.RemoveField(
            model_name='politician',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='politician',
            name='commentsdislikes',
        ),
        migrations.RemoveField(
            model_name='politician',
            name='commentslikes',
        ),
    ]
