# Generated by Django 2.2.7 on 2019-11-18 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gobiernoapp', '0002_auto_20191116_1530'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Comments'},
        ),
    ]
