# Generated by Django 2.2.7 on 2019-11-19 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gobiernoapp', '0004_auto_20191118_0612'),
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prov_name', models.CharField(max_length=500)),
                ('authority', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name_plural': 'Provinces',
                'ordering': ['prov_name'],
            },
        ),
        migrations.RemoveField(
            model_name='politician',
            name='region',
        ),
        migrations.AddField(
            model_name='politician',
            name='location_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='politician',
            name='photo_url',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
