# Generated by Django 2.2.7 on 2019-11-19 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gobiernoapp', '0005_auto_20191119_0325'),
    ]

    operations = [
        migrations.AddField(
            model_name='province',
            name='region',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
